name: 'PostgreSQL Proxy Action'
description: 'GitHub Action for proxying PostgreSQL over ssh'
author: 'virbyte'
inputs:
  postgre_host:
    description: 'PostgreSQL host'
    required: false
    default: 'localhost'
  postgre_port:
    description: 'PostgreSQL port'
    required: false
    default: 5432
  remote_host:
    description: 'Remote SSH host'
    required: true
  remote_port:
    description: 'Remote SSH port'
    required: false
    default: 22
  remote_user:
    description: 'Remote username'
    required: true
  remote_key:
    description: 'Keyfile for remote SSH server'
    required: true
  remote_key_pass:
    description: 'Keyfile passphrase'
    required: false
    default: ''
  switches:
    description: 'Extra OpenSSH client switches'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'send'
